export const CATEGORY_ICON_KEYS = [
  'briefcase',
  'trending-up',
  'laptop',
  'receipt',
  'landmark',
  'wallet',
  'banknote',
  'piggy-bank',
  'credit-card',
  'utensils',
  'coffee',
  'shopping-cart',
  'shopping-bag',
  'car',
  'bus',
  'bike',
  'fuel',
  'plane',
  'house',
  'wrench',
  'wifi',
  'smartphone',
  'party-popper',
  'gamepad',
  'music',
  'heart-pulse',
  'pill',
  'dumbbell',
  'gift',
  'scissors',
  'graduation-cap',
  'book',
  'baby',
  'paw',
  'sparkles',
] as const

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number]
