import {
  Apple,
  Baby,
  Bandage,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Bus,
  Cake,
  Calculator,
  Car,
  ChefHat,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  FileText,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  Handshake,
  HeartPulse,
  Hotel,
  House,
  Landmark,
  Laptop,
  Luggage,
  type LucideIcon,
  Music,
  Package,
  Palette,
  ParkingCircle,
  PartyPopper,
  PawPrint,
  Percent,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Receipt,
  School,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  SprayCan,
  Stethoscope,
  Ticket,
  TrainFront,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  UtensilsCrossed,
  Wallet,
  WashingMachine,
  Wifi,
  Wrench,
} from 'lucide-react'
import type { CategoryIconKey } from '@/lib/categoryIconKeys'

export { CATEGORY_ICON_KEYS, type CategoryIconKey } from '@/lib/categoryIconKeys'

export const CATEGORY_ICONS = {
  briefcase: Briefcase,
  'trending-up': TrendingUp,
  laptop: Laptop,
  receipt: Receipt,
  landmark: Landmark,
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  utensils: UtensilsCrossed,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  car: Car,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  house: House,
  wrench: Wrench,
  wifi: Wifi,
  smartphone: Smartphone,
  'party-popper': PartyPopper,
  gamepad: Gamepad2,
  music: Music,
  'heart-pulse': HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  gift: Gift,
  scissors: Scissors,
  'graduation-cap': GraduationCap,
  book: BookOpen,
  baby: Baby,
  paw: PawPrint,
  sparkles: Sparkles,
  'hand-coins': HandCoins,
  percent: Percent,
  calculator: Calculator,
  handshake: Handshake,
  shield: Shield,
  'building-2': Building2,
  'washing-machine': WashingMachine,
  'spray-can': SprayCan,
  hammer: Hammer,
  sofa: Sofa,
  truck: Truck,
  package: Package,
  parking: ParkingCircle,
  train: TrainFront,
  hotel: Hotel,
  luggage: Luggage,
  tv: Tv,
  shirt: Shirt,
  gem: Gem,
  stethoscope: Stethoscope,
  glasses: Glasses,
  bandage: Bandage,
  school: School,
  film: Clapperboard,
  ticket: Ticket,
  trophy: Trophy,
  palette: Palette,
  pizza: Pizza,
  beer: Beer,
  cake: Cake,
  'chef-hat': ChefHat,
  apple: Apple,
  'briefcase-business': BriefcaseBusiness,
  'file-text': FileText,
  'flower-2': Flower2,
} as const satisfies Record<CategoryIconKey, LucideIcon>
