import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  type LucideIcon,
  Music,
  PartyPopper,
  PawPrint,
  Pill,
  PiggyBank,
  Plane,
  Receipt,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  TrendingUp,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
} from 'lucide-react'
import type { CategoryIconKey } from '@/lib/categoryIconKeys'

export { CATEGORY_ICON_KEYS, type CategoryIconKey } from '@/lib/categoryIconKeys'

export const CATEGORY_ICONS = {
  briefcase: Briefcase,
  'trending-up': TrendingUp,
  laptop: Laptop,
  receipt: Receipt,
  landmark: Landmark,
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  utensils: UtensilsCrossed,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  car: Car,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  house: House,
  wrench: Wrench,
  wifi: Wifi,
  smartphone: Smartphone,
  'party-popper': PartyPopper,
  gamepad: Gamepad2,
  music: Music,
  'heart-pulse': HeartPulse,
  pill: Pill,
  dumbbell: Dumbbell,
  gift: Gift,
  scissors: Scissors,
  'graduation-cap': GraduationCap,
  book: BookOpen,
  baby: Baby,
  paw: PawPrint,
  sparkles: Sparkles,
} as const satisfies Record<CategoryIconKey, LucideIcon>
